# ---------------- qick configs ------------------
config:
    gen_chs:
        res_drive: {ch: 6, nqz: 1, mixer_freq: 2200, mux_freqs: [300, 0, 0, 0], 
            mux_gains: [0.8, 0.0, 0, 0], ro_ch: 0}
        q_drive: {ch: 2, nqz: 2}

    ro_chs:
        ro_0: {ch: 0, freq: 300, length: 1000, gen_ch: 6} # length in clk ticks

    waveforms:
        q_gauss: {shape: gaussian, sigma: 0.01, length: 0.05}
#        q_tanh: {shape: tanh_box, length: 0.08, ramp_width: 0.02}

    q_pulse_cfg:
        waveform: q_gauss
        ge_freq: 4875.45
        pi_gain: 12937
        pi2_gain: 6519
        t2r_freq: 4875.88
        ef_freq: 4691.395

    res_pulse_config:
        style: const
        length: 2 # us

    adc_trig_offset: 90  # [clock ticks]
    relax_delay: 200  # [us]
    msmt_leakout_time: 1 # [us] ~3*cavity_T1


# ---------------- miscellaneous infos ------------------
info:
    PyroServer: myqick216-01
    rotResult: {'g_val': -108.13987573558575, 'e_val': 53.24940494399092, 'rot_angle': -37.40041772235114}
    dataPath: L:\Data\chen_wang\cooldown_20220926\\
    sampleName: ChenWang



